### ISSUE TITLE
Security:  Ensure that swapping of tokens has a max limit of 1000 tokens per swap.

### ISSUE THREAD

**Issue by dorglkramer** [dOrgTech/starkware-demo#19]
There is a security risk that someone could generate the max number of tokens available and swap them all for a second set of tokens, thus causing some problems with the demo. Additionally, I wonder if we should do some lazy checks on the number of tokens a given user has per "wallet ID" to prevent them from trying to generate more than they need to reasonably conduct a demo.

**Comment by eliobricenov** [comment]
@dorglkramer I can add the 1000 tokens limit but I'm not sure if we'll have access to know how many tokens are "reasonably conduct a demo", unless they tell us the exact amount.
