### ISSUE TITLE
Determine method in which we will generate "wallet equivalent"

### ISSUE THREAD

**Issue by dorglkramer** [dOrgTech/starkware-demo#3]
Determine method in which we will generate "wallet equivalent" for user session (since there is no wallet), and be sure it is available through the application (cookie? local storage?, react context)

**Comment by bhanusanghi** [comment]
Thinking about using local storage to store a randomly generated UUID for every user on their first visit or if the local storage variable is not found.
Local Storage will persist throughout and we won't have to ask user to accept cookies.
Similar thing is done by many platforms including Medium to limit your free articles. 
React Context won't be persisted.

**Comment by dorglkramer** [comment]
Do we need to worry about UUID format? Like something that mimics a wallet address (since we will need to conduct the swap, and presumably these artificial UUID will be what we use)

**Comment by bhanusanghi** [comment]
Added a user Context that will be used throughout the app. 
Will be adding the interactions like - generating a user id, storing context in local storage next.
